[package]
name = "polars_bindings"
version = "0.1.0"
edition = "2018"
build="build/build.rs"

[lib]
name = "polars_bindings"
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
cbindgen = "0.14.3"
