[package]
name = "polars_bindings"
version = "0.1.0"
edition = "2018"

[workspace]
# prevents package from thinking it's in the workspace

[dependencies]
polars = { version = "0.12.1", features = [
    "parquet",
    "simd",
    "json",
    "strings",
    "temporal",
    "random",
    "object",
    "ipc"
]}

[lib]
name = "polars_bindings"
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
cbindgen = "0.19.0"
